redis:
    redis_host: 127.0.0.1:6379
    redis_pwd:
mongoDb:
    mongo_host: mongodb://admin:123456@127.0.0.1:27017
    db_name: birdtalk
scyllaDb:
    scylla_host: 8.140.203.92:9042
    user: cassandra
    pwd: Tjj.31415
kafka:
    kafka_host:

server:
    host: 0.0.0.0
    port: 7817
    host_index: 1
    host_name: node1
    group_msg_queue_len: 100
    workers: 1
    schema: https
    cert: ./certs/cert.pem
    key: ./certs/key.pem
    friend_making: false
    email:
        host: email.sina.com
        user: robin
        pwd: 123456
        tls: true

email:
    smtp_addr: smtp.sina.com
    smtp_port: 25
    smtp_helo_host: sina.com
    user_name: tinodemaster@sina.com
    user_pwd: 7ee60df2d8b390fd
    tls_insecure_skip_verify: false
    auth_type: login

